### ISSUE TITLE
对于有些json的支持好像还是有问题

### ISSUE THREAD

**Issue by wonderffee** [sutar/JSON2Mantle#5]
Traceback (most recent call last):
  File "/usr/local/bin/json2mantle", line 9, in <module>
    load_entry_point('JSON2Mantle==0.0.8', 'console_scripts', 'json2mantle')()
  File "/Library/Python/2.7/site-packages/json2mantle/cli.py", line 272, in main
    j2m.generate_properties(dict_data, class_name)
  File "/Library/Python/2.7/site-packages/json2mantle/cli.py", line 219, in generate_properties
    self.properties = self.extract_properties(dict_data, class_name)
  File "/Library/Python/2.7/site-packages/json2mantle/cli.py", line 155, in extract_properties
    sub_model = self.extract_properties(value[0], new_class_name)
  File "/Library/Python/2.7/site-packages/json2mantle/cli.py", line 155, in extract_properties
    sub_model = self.extract_properties(value[0], new_class_name)
IndexError: list index out of range

**Comment by iflyingboots** [comment]
Hi,

能否提供下你测试的 JSON 文件（可以放到 gist 之类的地方）？我调试下。

**Comment by wonderffee** [comment]
我放到这里了：
https://gist.github.com/wonderffee/863428534904caa6a638

**Comment by wonderffee** [comment]
还有一个也有问题：
Generating "List2Model" files
Generating "ShopdataModel" files
Generating "GoodsdataModel" files
Generating "CommentdataModel" files
Generating "ImagesModel" files
Traceback (most recent call last):
  File "/usr/local/bin/json2mantle", line 9, in <module>
    load_entry_point('JSON2Mantle==0.0.8', 'console_scripts', 'json2mantle')()
  File "/Library/Python/2.7/site-packages/json2mantle/cli.py", line 272, in main
    j2m.generate_properties(dict_data, class_name)
  File "/Library/Python/2.7/site-packages/json2mantle/cli.py", line 219, in generate_properties
    self.properties = self.extract_properties(dict_data, class_name)
  File "/Library/Python/2.7/site-packages/json2mantle/cli.py", line 140, in extract_properties
    sub_model = self.extract_properties(value, new_class_name)
  File "/Library/Python/2.7/site-packages/json2mantle/cli.py", line 155, in extract_properties
    sub_model = self.extract_properties(value[0], new_class_name)
  File "/Library/Python/2.7/site-packages/json2mantle/cli.py", line 135, in extract_properties
    for original_name, value in dict_data.items():
AttributeError: 'unicode' object has no attribute 'items'

json链接：https://gist.github.com/wonderffee/425c402c203ab8214579

**Comment by iflyingboots** [comment]
已修复，欢迎重新 pip 安装。

但是对于 https://gist.github.com/wonderffee/863428534904caa6a638 这个文件，`subcatogroy` 无法生成，因为第一个元素是空的。建议用 JSON2Mantle 之前先对文件进行下处理，提供类似 22 行的那一项数据。

**Comment by wonderffee** [comment]
一定要是第一个元素吗，是不是可以遍历一下找出不为空的元素？

**Comment by iflyingboots** [comment]
当然可以遍历，不过得改一些代码。不过我觉得如果提供一个典型的、有效的 JSON 样本作为输入不是更方便而且更有意义吗？ :smiley:
