### ISSUE TITLE
Access addressbook

### ISSUE THREAD

**Issue by qiaoyan** [sutar/JSON2Mantle#6]
Hi,

Great work. Why need access addressbook? After decline raise a error:
Traceback (most recent call last):
  File "/usr/local/bin/json2mantle", line 9, in <module>
    load_entry_point('JSON2Mantle==0.0.9', 'console_scripts', 'json2mantle')()
  File "/Library/Python/2.7/site-packages/json2mantle/cli.py", line 263, in main
    j2m = JSON2Mantle()
  File "/Library/Python/2.7/site-packages/json2mantle/cli.py", line 32, in **init**
    'author': utils.get_current_user_name(),
  File "/Library/Python/2.7/site-packages/json2mantle/utils.py", line 63, in get_current_user_name
    people = address_book.people()
AttributeError: 'NoneType' object has no attribute 'people'

**Comment by iflyingboots** [comment]
Hi,

Asking for the access of AddressBook is a way to get the author name, just like what Xcode does. It will do no harm.
